#!/usr/bin/env python3
"""
build_devices.py — produce the 131 renamed, path-clean, category-sorted M4L devices.

For every original device in original_ppooll_sources/devices_amxd/ it:
  1. parses the .amxd patcher JSON,
  2. removes machine-specific / absolute paths (the ~/Desktop/ppooll dependency-cache
     bootpaths) so the device resolves purely via the installed ppooll Max package,
  3. re-packs a byte-faithful, valid .amxd (preserving the original Live device type
     by default; with --retag it applies the suggested live_type from device_map.json),
  4. writes it to devices/<category>/<Clear Name> — <act>.amxd,
  5. statically validates the output (JSON round-trip + zero machine paths + source act
     present in the bundled runtime),
  6. records a per-device status row in build_report/.

It NEVER alters parameter names, GUI geometry, or patch logic — those live inside the
shared ppooll act patchers and require Max + Ableton to edit and verify safely.

Usage:
    python3 tools/build_devices.py            # preserve original device type (default)
    python3 tools/build_devices.py --retag    # also set suggested Live device type
    python3 tools/build_devices.py --clean     # wipe devices/* first
"""
import json
import os
import re
import sys

import amxd_lib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC_DIR = os.path.join(ROOT, "original_ppooll_sources", "devices_amxd")
DEV_DIR = os.path.join(ROOT, "devices")
RUNTIME_ACTS = os.path.join(ROOT, "dependencies", "ppooll", "patchers", "ppooll.acts")
REPORT_DIR = os.path.join(ROOT, "build_report")
MAP = os.path.join(HERE, "device_map.json")

# substrings that mark a machine-specific / non-portable path
BAD_PATH = re.compile(r"(/Users/|Desktop/ppooll|/Applications/|^[A-Za-z]:\\\\|/home/)")


def sanitize_filename(clear_name: str, act: str) -> str:
    name = clear_name.replace("/", "-").strip()
    # collapse whitespace
    name = re.sub(r"\s+", " ", name)
    return f"{name} — {act}.amxd"  # "Clear Name — act.amxd"


def strip_machine_paths(obj):
    """Remove machine-specific dependency-cache bootpaths; return (obj, removed_list)."""
    removed = []
    p = obj["patcher"]
    dc = p.get("dependency_cache", [])
    new_dc = []
    for entry in dc:
        bp = entry.get("bootpath", "")
        if bp and BAD_PATH.search(bp):
            if entry.get("implicit"):
                # implicit deps are auto-regenerated by Max from the search path; drop entirely
                removed.append(f"{entry.get('name','?')} (implicit, bootpath {bp})")
                continue
            # explicit dep: keep the file reference but drop the machine path
            removed.append(f"{entry.get('name','?')} (bootpath {bp} -> removed)")
            entry = {k: v for k, v in entry.items() if k != "bootpath"}
        new_dc.append(entry)
    p["dependency_cache"] = new_dc
    return obj, removed


def find_remaining_paths(obj):
    """Return any machine-specific path substrings still present anywhere in the JSON."""
    s = json.dumps(obj, ensure_ascii=False)
    return sorted({m.group(0) for m in BAD_PATH.finditer(s)})


def main():
    retag = "--retag" in sys.argv
    clean = "--clean" in sys.argv

    devmap = {d["act"]: d for d in json.load(open(MAP, encoding="utf-8"))["devices"]}
    os.makedirs(REPORT_DIR, exist_ok=True)

    if clean:
        for root, _, files in os.walk(DEV_DIR):
            for f in files:
                if f.endswith(".amxd"):
                    os.remove(os.path.join(root, f))

    rows = []
    errors = []
    for act, info in sorted(devmap.items()):
        src = os.path.join(SRC_DIR, f"live.ppooll.{act}.amxd")
        cat = info["category"]
        out_name = sanitize_filename(info["clear_name"], act)
        out_dir = os.path.join(DEV_DIR, cat)
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, out_name)

        status = "OK"
        notes = []
        removed = []

        if not os.path.isfile(src):
            errors.append(f"{act}: source .amxd missing")
            status = "ERROR"
            rows.append((act, info, out_name, status, ["source missing"], []))
            continue

        orig_type = amxd_lib.device_type(src)
        new_type = info["live_type"].encode() if retag else None

        def mutate(obj, _removed=removed):
            obj, rm = strip_machine_paths(obj)
            _removed.extend(rm)
            return obj

        try:
            amxd_lib.repack_file(src, out_path, mutate=mutate, new_type=new_type)
        except Exception as e:  # noqa
            errors.append(f"{act}: repack failed: {e}")
            status = "ERROR"
            rows.append((act, info, out_name, status, [str(e)], removed))
            continue

        # ---- static validation ----
        _, _, out_obj = amxd_lib.read(out_path)
        remaining = find_remaining_paths(out_obj)
        if remaining:
            status = "WARN"
            notes.append("residual paths: " + ", ".join(remaining))

        act_src = os.path.join(RUNTIME_ACTS, f"{act}.maxpat")
        if not os.path.isfile(act_src):
            status = "WARN"
            notes.append(f"act patcher {act}.maxpat not found in bundled runtime")

        if info["extra_packages"]:
            notes.append("needs package(s): " + ", ".join(info["extra_packages"]))
        if info["extra_packages_inferred"]:
            notes.append("likely needs: " + ", ".join(info["extra_packages_inferred"]))

        final_type = (new_type or orig_type)
        notes.append(f"live_type={final_type.decode()} ({amxd_lib.TYPE_NAMES.get(final_type,'?')})")

        rows.append((act, info, out_name, status, notes, removed))

    # ---- write reports ----
    report = {
        "retag": retag,
        "total": len(rows),
        "ok": sum(1 for r in rows if r[3] == "OK"),
        "warn": sum(1 for r in rows if r[3] == "WARN"),
        "error": sum(1 for r in rows if r[3] == "ERROR"),
        "devices": [
            {
                "act": act,
                "clear_name": info["clear_name"],
                "category": info["category"],
                "output": f"devices/{info['category']}/{out_name}",
                "status": status,
                "notes": notes,
                "paths_removed": removed,
            }
            for (act, info, out_name, status, notes, removed) in rows
        ],
    }
    json.dump(report, open(os.path.join(REPORT_DIR, "build_report.json"), "w"),
              indent=2, ensure_ascii=False)

    print(f"Built {report['total']} devices: "
          f"{report['ok']} OK, {report['warn']} WARN, {report['error']} ERROR "
          f"(retag={retag})")
    total_removed = sum(len(r[5]) for r in rows)
    print(f"Machine-specific paths removed: {total_removed} entries across all devices")
    if errors:
        print("ERRORS:")
        for e in errors:
            print("  -", e)
        sys.exit(1)


if __name__ == "__main__":
    main()
